// <auto-generated />
using System;
using GBC_Ticketing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GBCVirtualEventTicketingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251015145722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GBC_Ticketing.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Online educational seminars",
                            Name = "Webinar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Live music performances",
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hands-on learning sessions",
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Professional gatherings",
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("GBC_Ticketing.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 100,
                            CategoryId = 1,
                            EventDate = new DateTime(2025, 11, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 49.99m,
                            Title = "Web Development Bootcamp"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 3,
                            CategoryId = 2,
                            EventDate = new DateTime(2025, 11, 20, 19, 30, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 75.00m,
                            Title = "Jazz Night Live"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 50,
                            CategoryId = 3,
                            EventDate = new DateTime(2025, 11, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 89.99m,
                            Title = "UI/UX Design Workshop"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTickets = 200,
                            CategoryId = 4,
                            EventDate = new DateTime(2025, 12, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 199.99m,
                            Title = "Tech Innovation Conference 2025"
                        },
                        new
                        {
                            Id = 5,
                            AvailableTickets = 0,
                            CategoryId = 2,
                            EventDate = new DateTime(2025, 11, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 59.99m,
                            Title = "Rock Festival Virtual"
                        },
                        new
                        {
                            Id = 6,
                            AvailableTickets = 4,
                            CategoryId = 1,
                            EventDate = new DateTime(2025, 11, 18, 15, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 29.99m,
                            Title = "Digital Marketing Webinar"
                        });
                });

            modelBuilder.Entity("GBC_Ticketing.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("GBC_Ticketing.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerTicket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("GBC_Ticketing.Models.Event", b =>
                {
                    b.HasOne("GBC_Ticketing.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GBC_Ticketing.Models.PurchaseItem", b =>
                {
                    b.HasOne("GBC_Ticketing.Models.Event", "Event")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBC_Ticketing.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("GBC_Ticketing.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("GBC_Ticketing.Models.Event", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("GBC_Ticketing.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
